//HintName: SimpleTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using UXUnit;

namespace UXUnit.Generated
{
    internal static class SimpleTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "SimpleTests",
                CreateInstance = () => new global::SimpleTests(),
                TestDispatch = async (receiver, methodName, theoryArgs) =>
                {
                    switch (methodName)
                    {
                        case "PassingTest":
                        {
                            ((global::SimpleTests)receiver!).PassingTest();
                            break;
                        }
                        default:
                            throw new global::System.InvalidOperationException("Unknown test method: " + methodName);
                    }
                    await global::System.Threading.Tasks.Task.CompletedTask;
                },
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "PassingTest",
                        IsAsync = false,
                        IsStatic = false,
                    },
                },
            };
        }
    }
}
