//HintName: AsyncTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using UXUnit;

namespace UXUnit.Generated
{
    internal static class AsyncTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "AsyncTests",
                CreateInstance = () => new global::AsyncTests(),
                TestDispatch = async (receiver, methodName, theoryArgs) =>
                {
                    switch (methodName)
                    {
                        case "AsyncPassingTest":
                        {
                            await ((global::AsyncTests)receiver!).AsyncPassingTest();
                            break;
                        }
                        default:
                            throw new global::System.InvalidOperationException("Unknown test method: " + methodName);
                    }
                    await global::System.Threading.Tasks.Task.CompletedTask;
                },
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "AsyncPassingTest",
                        IsAsync = true,
                        IsStatic = false,
                    },
                },
            };
        }
    }
}
