//HintName: StaticTestClass_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using UXUnit;

namespace UXUnit.Generated
{
    internal static class StaticTestClass_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "StaticTestClass",
                CreateInstance = () => null,
                TestDispatch = async (receiver, methodName, theoryArgs) =>
                {
                    switch (methodName)
                    {
                        case "StaticFact":
                        {
                            global::StaticTestClass.StaticFact();
                            break;
                        }
                        default:
                            throw new global::System.InvalidOperationException("Unknown test method: " + methodName);
                    }
                    await global::System.Threading.Tasks.Task.CompletedTask;
                },
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "StaticFact",
                        IsAsync = false,
                        IsStatic = true,
                    },
                },
            };
        }
    }
}
