//HintName: MixedTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using UXUnit;

namespace UXUnit.Generated
{
    internal static class MixedTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "MixedTests",
                AssemblyName = "GeneratesMetadataForMultipleTestMethods",
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "Test1",
                        IsAsync = false,
                        IsStatic = false,
                        Body = async (ct) =>
                        {
                            var instance = new MixedTests();
                            instance.Test1();
                            if (instance is IDisposable disposable)
                                disposable.Dispose();
                        }
                    },
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "Test2",
                        IsAsync = false,
                        IsStatic = false,
                        Body = async (ct) =>
                        {
                            var instance = new MixedTests();
                            instance.Test2();
                            if (instance is IDisposable disposable)
                                disposable.Dispose();
                        }
                    },
                    new TestMethodMetadata.Theory
                    {
                        MethodName = "StringTest",
                        IsAsync = false,
                        IsStatic = false,
                        TestCases = new TestCaseMetadata[]
                        {
                            new TestCaseMetadata
                            {
                                Arguments = new object?[] { "hello" }
                            },
                            new TestCaseMetadata
                            {
                                Arguments = new object?[] { "world" }
                            },
                        },
                        ParameterizedBody = async (args, ct) =>
                        {
                            var instance = new MixedTests();
                            instance.StringTest((string)args[0]!);
                            if (instance is IDisposable disposable)
                                disposable.Dispose();
                        }
                    },
                },
            };
        }
    }
}
