//HintName: MathTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using UXUnit;

namespace UXUnit.Generated
{
    internal static class MathTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "MathTests",
                AssemblyName = "GeneratesMetadataForTheoryWithInlineData",
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Theory
                    {
                        MethodName = "AddTest",
                        IsAsync = false,
                        IsStatic = false,
                        TestCases = new TestCaseMetadata[]
                        {
                            new TestCaseMetadata
                            {
                                Arguments = new object?[] { 1, 2, 3 }
                            },
                            new TestCaseMetadata
                            {
                                Arguments = new object?[] { 5, 7, 12 }
                            },
                        },
                        ParameterizedBody = async (args, ct) =>
                        {
                            var instance = new MathTests();
                            instance.AddTest((int)args[0]!, (int)args[1]!, (int)args[2]!);
                            if (instance is IDisposable disposable)
                                disposable.Dispose();
                        }
                    },
                },
            };
        }
    }
}
