//HintName: AsyncTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using UXUnit;

namespace UXUnit.Generated
{
    internal static class AsyncTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "AsyncTests",
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "AsyncPassingTest",
                        IsAsync = true,
                        IsStatic = false,
                        Body = async (ct) =>
                        {
                            var instance = new AsyncTests();
                            await instance.AsyncPassingTest();
                            if (instance is IDisposable disposable)
                                disposable.Dispose();
                        }
                    },
                },
            };
        }
    }
}
