//HintName: MixedTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using UXUnit;

namespace UXUnit.Generated
{
    internal static class MixedTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "MixedTests",
                CreateInstance = () => new global::MixedTests(),
                TestDispatch = async (receiver, methodName, theoryArgs) =>
                {
                    switch (methodName)
                    {
                        case "Test1":
                        {
                            ((global::MixedTests)receiver!).Test1();
                            break;
                        }
                        case "Test2":
                        {
                            ((global::MixedTests)receiver!).Test2();
                            break;
                        }
                        case "StringTest":
                        {
                            ((global::MixedTests)receiver!).StringTest((string)theoryArgs!);
                            break;
                        }
                        default:
                            throw new global::System.InvalidOperationException("Unknown test method: " + methodName);
                    }
                    await global::System.Threading.Tasks.Task.CompletedTask;
                },
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "Test1",
                        IsAsync = false,
                        IsStatic = false,
                    },
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "Test2",
                        IsAsync = false,
                        IsStatic = false,
                    },
                    new TestMethodMetadata.Theory
                    {
                        MethodName = "StringTest",
                        IsAsync = false,
                        IsStatic = false,
                        TestCases = new TestCaseInfo[]
                        {
                            new TestCaseInfo
                            {
                                Arguments = "hello",
                                DisplayName = "input: \\\"hello\\\"",
                            },
                            new TestCaseInfo
                            {
                                Arguments = "world",
                                DisplayName = "input: \\\"world\\\"",
                            },
                        },
                    },
                },
            };
        }
    }
}
