//HintName: TestClass1_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using UXUnit;

namespace UXUnit.Generated
{
    internal static class TestClass1_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "TestClass1",
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "Test1",
                        IsAsync = false,
                        IsStatic = false,
                        Body = async (ct) =>
                        {
                            var instance = new TestClass1();
                            instance.Test1();
                            if (instance is IDisposable disposable)
                                disposable.Dispose();
                        }
                    },
                },
            };
        }
    }
}
