//HintName: TestRegistry.g.cs
// <auto-generated/>
#nullable enable

using UXUnit;

namespace UXUnit.Generated
{
    internal static class TestRegistry
    {
        public static TestClassMetadata[] GetAllTests()
        {
            return new TestClassMetadata[]
            {
                MixedTests_Metadata.GetMetadata(),
            };
        }
    }
}
