//HintName: MathTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using NXTest;

namespace NXTest.Generated
{
    internal static class MathTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "MathTests",
                CreateInstance = () => new global::MathTests(),
                TestDispatch = async (receiver, methodName, theoryArgs) =>
                {
                    switch (methodName)
                    {
                        case "AddTest":
                        {
                            var args = (global::System.ValueTuple<int, int, int>)theoryArgs!;
                            ((global::MathTests)receiver!).AddTest(args.Item1, args.Item2, args.Item3);
                            break;
                        }
                        default:
                            throw new global::System.InvalidOperationException("Unknown test method: " + methodName);
                    }
                    await global::System.Threading.Tasks.Task.CompletedTask;
                },
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Theory
                    {
                        MethodName = "AddTest",
                        IsAsync = false,
                        IsStatic = false,
                        TestCases = new TestCaseInfo[]
                        {
                            new TestCaseInfo
                            {
                                Arguments = new global::System.ValueTuple<int, int, int>(1, 2, 3),
                                DisplayName = "a: 1, b: 2, sum: 3",
                            },
                            new TestCaseInfo
                            {
                                Arguments = new global::System.ValueTuple<int, int, int>(5, 7, 12),
                                DisplayName = "a: 5, b: 7, sum: 12",
                            },
                        },
                    },
                },
            };
        }
    }
}
