//HintName: StaticMethodTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using NXTest;

namespace NXTest.Generated
{
    internal static class StaticMethodTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "StaticMethodTests",
                CreateInstance = () => new global::StaticMethodTests(),
                TestDispatch = async (receiver, methodName, theoryArgs) =>
                {
                    switch (methodName)
                    {
                        case "StaticPassingTest":
                        {
                            global::StaticMethodTests.StaticPassingTest();
                            break;
                        }
                        default:
                            throw new global::System.InvalidOperationException("Unknown test method: " + methodName);
                    }
                    await global::System.Threading.Tasks.Task.CompletedTask;
                },
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "StaticPassingTest",
                        IsAsync = false,
                        IsStatic = true,
                    },
                },
            };
        }
    }
}
