//HintName: TestRegistry.g.cs
// <auto-generated/>
#nullable enable

using NXTest;

namespace NXTest.Generated
{
    internal static class TestRegistry
    {
        public static TestClassMetadata[] GetAllTests()
        {
            return new TestClassMetadata[]
            {
                AsyncTests_Metadata.GetMetadata(),
            };
        }
    }
}
