//HintName: DerivedTests_Metadata.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using NXTest;

namespace NXTest.Generated
{
    internal static class DerivedTests_Metadata
    {
        public static TestClassMetadata GetMetadata()
        {
            return
            new TestClassMetadata
            {
                ClassName = "DerivedTests",
                CreateInstance = () => new global::DerivedTests(),
                TestDispatch = async (receiver, methodName, theoryArgs) =>
                {
                    switch (methodName)
                    {
                        case "InheritedFact":
                        {
                            ((global::DerivedTests)receiver!).InheritedFact();
                            break;
                        }
                        case "InheritedTheory":
                        {
                            ((global::DerivedTests)receiver!).InheritedTheory((int)theoryArgs!);
                            break;
                        }
                        default:
                            throw new global::System.InvalidOperationException("Unknown test method: " + methodName);
                    }
                    await global::System.Threading.Tasks.Task.CompletedTask;
                },
                TestMethods = new TestMethodMetadata[]
                {
                    new TestMethodMetadata.Fact
                    {
                        MethodName = "InheritedFact",
                        IsAsync = false,
                        IsStatic = false,
                    },
                    new TestMethodMetadata.Theory
                    {
                        MethodName = "InheritedTheory",
                        IsAsync = false,
                        IsStatic = false,
                        TestCases = new TestCaseInfo[]
                        {
                            new TestCaseInfo
                            {
                                Arguments = 42,
                                DisplayName = "value: 42",
                            },
                        },
                    },
                },
            };
        }
    }
}
